version: "3"

services:
    webapp:
        build: .
        ports:
            - ${WEBAPP_PORT}:8000
        command: bash -c "while true; do echo 'I am alive!'; sleep 3600; done"
        environment:
            - C_FORCE_ROOT=true
        volumes:
            - .:/webapp

    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        volumes:
            - postgres-volume:/var/lib/postgresql/data

volumes:
    postgres-volume:
