version: "3"

services:
    django:
        build: .
        ports:
            - ${DJANGO_PORT}:8000
        command: bash -c "while true; do echo 'I am alive!'; sleep 3600; done"
        environment:
            - C_FORCE_ROOT=true
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        volumes:
            - .:/webapp
        links:
            - postgres

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        volumes:
            - postgres-volume:/var/lib/postgresql/data

volumes:
    postgres-volume:
